name: FWFortress
version: ${project.version}
main: me.architetto.fwfortress.FWFortress
api-version: 1.16
authors: [ Architetto ]
depend: [ Towny ]
commands:
  fwfortress:
    description: Plugin per la gestione delle fortezze.
    aliases:
      - fwf

permissions:
  fwfortress.create:
    description: create command permission
    default: op
  fwfortress.delete:
    description: delete command permission
    default: op
  fwfortress.reload:
    description: reload command permission
    default: op
  fwfortress.stop:
    description: stop command permission
    default: op
  fwfortress.teleport:
    description: teleport command permission
    default: op
  fwfortress.info:
    description: info command permission
    default: true
  fwfortress.invade:
    description: invade command permission
    default: op
  fwfortress.build:
    description: allow to build inside fortress area
    default: op
