## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ##
## * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * ##
## *                         ███████╗██╗    ██╗                          * ##
## *                         ██╔════╝██║    ██║                          * ##
## *                         █████╗  ██║ █╗ ██║                          * ##
## *                         ██╔══╝  ██║███╗██║                          * ##
## *                         ██║     ╚███╔███╔╝                          * ##
## *                         ╚═╝      ╚══╝╚══╝                           * ##
## * ███████╗ ██████╗ ██████╗ ████████╗██████╗ ███████╗███████╗███████╗  * ##
## * ██╔════╝██╔═══██╗██╔══██╗╚══██╔══╝██╔══██╗██╔════╝██╔════╝██╔════╝  * ##
## * █████╗  ██║   ██║██████╔╝   ██║   ██████╔╝█████╗  ███████╗███████╗  * ##
## * ██╔══╝  ██║   ██║██╔══██╗   ██║   ██╔══██╗██╔══╝  ╚════██║╚════██║  * ##
## * ██║     ╚██████╔╝██║  ██║   ██║   ██║  ██║███████╗███████║███████║  * ##
## * ╚═╝      ╚═════╝ ╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝  * ##
## *                         Made by: Architetto                         * ##
## *     SOURCE CODE: https://github.com/ForgottenWorld/FWFortress       * ##
## * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * ##
## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ##

FORTRESS_HP: 1000

BATTLE_TIME_LIMIT: 1800

START_BATTLE_DELAY : 15