## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ##
## * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * ##
## *                         ███████╗██╗    ██╗                          * ##
## *                         ██╔════╝██║    ██║                          * ##
## *                         █████╗  ██║ █╗ ██║                          * ##
## *                         ██╔══╝  ██║███╗██║                          * ##
## *                         ██║     ╚███╔███╔╝                          * ##
## *                         ╚═╝      ╚══╝╚══╝                           * ##
## * ███████╗ ██████╗ ██████╗ ████████╗██████╗ ███████╗███████╗███████╗  * ##
## * ██╔════╝██╔═══██╗██╔══██╗╚══██╔══╝██╔══██╗██╔════╝██╔════╝██╔════╝  * ##
## * █████╗  ██║   ██║██████╔╝   ██║   ██████╔╝█████╗  ███████╗███████╗  * ##
## * ██╔══╝  ██║   ██║██╔══██╗   ██║   ██╔══██╗██╔══╝  ╚════██║╚════██║  * ##
## * ██║     ╚██████╔╝██║  ██║   ██║   ██║  ██║███████╗███████║███████║  * ##
## * ╚═╝      ╚═════╝ ╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝  * ##
## *                         Made by: Architetto                         * ##
## *     SOURCE CODE: https://github.com/ForgottenWorld/FWFortress       * ##
## * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * ##
## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ##

FORTRESS_HP: 200

BATTLE_TIME_LIMIT: 300

START_BATTLE_DELAY: 15

DISTANCE_BETWEEN_FORTRESSES: 30

MAX_GROUND_DISTANCE: 25

BATTLE_COOLDOWN: 1 #hour
