## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ##
## * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * ##
## *                         ███████╗██╗    ██╗                          * ##
## *                         ██╔════╝██║    ██║                          * ##
## *                         █████╗  ██║ █╗ ██║                          * ##
## *                         ██╔══╝  ██║███╗██║                          * ##
## *                         ██║     ╚███╔███╔╝                          * ##
## *                         ╚═╝      ╚══╝╚══╝                           * ##
## * ███████╗ ██████╗ ██████╗ ████████╗██████╗ ███████╗███████╗███████╗  * ##
## * ██╔════╝██╔═══██╗██╔══██╗╚══██╔══╝██╔══██╗██╔════╝██╔════╝██╔════╝  * ##
## * █████╗  ██║   ██║██████╔╝   ██║   ██████╔╝█████╗  ███████╗███████╗  * ##
## * ██╔══╝  ██║   ██║██╔══██╗   ██║   ██╔══██╗██╔══╝  ╚════██║╚════██║  * ##
## * ██║     ╚██████╔╝██║  ██║   ██║   ██║  ██║███████╗███████║███████║  * ##
## * ╚═╝      ╚═════╝ ╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝  * ##
## *                         Made by: Architetto                         * ##
## *     SOURCE CODE: https://github.com/ForgottenWorld/FWFortress       * ##
## * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * ##
## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ##

FORTRESS_HP: 200

REPAIR_PERCENTAGE: 25

REPAIR_COST: 10000

REPAIR_COOLDOWN: 24 #hour

MAX_DAMAGE_FOR_SECOND: 10

BATTLE_TIME_LIMIT: 300

START_BATTLE_DELAY: 15

DISTANCE_BETWEEN_FORTRESSES: 30

MAX_GROUND_DISTANCE: 25

MIN_INVADERS: 3

FORTRESS_BORDER_DAMAGE: 6

BATTLE_COOLDOWN: 1 #hour

#Mon,Tue,Wed,Thu,Fri,Sat,Sun
DATE: ['Mon','Tue','Wed','Thu','Fri','Sat' ,'Sun']

TIME_RANGE: [18,22]

INVADE_ALLIED_FORTRESS: false
